-- Intentionally empty.
-- Required system records are maintained by db_bootstrap.php / Treasury\DatabaseBootstrap.
-- User-created source apps, GL revenue accounts, GL expense accounts and admins should be created from the web UI.
